language: minimum

addons:
  apt:
    update: true

before_install:
  - sudo apt-get install wget unzip

install:
  - wget -O packer.zip https://releases.hashicorp.com/packer/1.3.3/packer_1.3.3_linux_amd64.zip
  - unzip -d /usr/local/bin packer.zip
  - rm packer.zip

script: packer validate -var-file=centos7.json packer-centos.json
